ARG NODE_VERSION_NUMBER=18
ARG PYTHON_VERSION_NUMBER=3.9
ARG PYTHON_IMAGE_VERSION=${PYTHON_VERSION_NUMBER}-slim

FROM python:${PYTHON_IMAGE_VERSION} AS backend-build
ARG NODE_VERSION_NUMBER

WORKDIR /app-dependencies
# Copy the frontend package file to install frontend dependencies from
COPY frontend/package.json ./
# Copy the backend requirements file to install backend dependencies from
COPY backend/requirements.txt ./

# Install global dependencies for compiling C, and running both backend and frontend
RUN apt-get update && \
    apt-get install -y build-essential graphviz && \
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION_NUMBER}.x | bash - && \
    apt-get install -y nodejs=${NODE_VERSION_NUMBER}.* npm && \
    pip install -r requirements.txt && \
    npm install

# Expose the necessary ports
EXPOSE 5000
# Set environment variables if necessary (optional)
ENV FLASK_APP=backend/api/api.py
# Command to build cython metric and symlink node modules to frontend app directory
CMD ["sh", "-c", "\
    cd /app/backend/api/src/machine_learning/models/model_types/k_nearest_neighbours/custom_metric && \
    python3 setup.py build_ext --inplace && \
    echo 'Custom metric build completed' && \
    ln -s /app-dependencies/node_modules /app/frontend/node_modules && \
    echo 'Node modules symlinked' && \
    cd /app && \
    bash \
"]
