ARG PYTHON_VERSION=3.9-slim

# Build stage
FROM python:${PYTHON_VERSION} AS builder
# Install global dependencies for compiling C extensions
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        curl \
        gnupg \
        ca-certificates \
        apt-transport-https && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
# Install Python build tools
RUN pip install --no-cache-dir setuptools wheel
# Set working directory
WORKDIR /backend
# Copy the backend requirements (before source code so can keep dependencies cached through code changes)
COPY backend/requirements.txt ./
# Install backend dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Copy the backend source code
COPY backend/ ./
# Run setup.py to build Cython custom metric module
WORKDIR /backend/api/src/machine_learning/models/model_types/k_nearest_neighbours/custom_metric
RUN python3 setup.py build_ext --inplace

# Runtime stage
FROM python:${PYTHON_VERSION}
# Install global dependencies
RUN apt-get update && \
    apt-get install -y graphviz curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
# Set working directory
WORKDIR /backend
# Copy the backend source code and installed dependencies from the builder stage
COPY --from=builder /backend/api/ /backend/api/
COPY --from=builder /usr/local/lib/python${PYTHON_VERSION%.*}/site-packages /usr/local/lib/python${PYTHON_VERSION%.*}/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
# Expose the necessary port
EXPOSE 5000
# Command to run backend (Flask API only, no static file serving)
CMD ["sh", "-c", "python3 -m flask run --host=0.0.0.0 --port=5000"]
