version: '3.8'

volumes:
    frontend-node_modules:
    frontend-build:
    dotnet-obj:
    dotnet-bin:
    backend-pycache:

services:
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        container_name: mywebsite-dev
        ports:
            - '3000:3000'
            - '5000:5000'
            - '5001:5001'
        volumes:
            - ../:/app
            - frontend-node_modules:/app/frontend/node_modules
            - frontend-build:/app/frontend/build
            - dotnet-obj:/app/dotnet/obj
            - dotnet-bin:/app/dotnet/bin
            - backend-pycache:/app/backend/__pycache__
        environment:
            - PYTHONUNBUFFERED=1
            - FLASK_APP=backend/api/api.py
            - STATIC_FOLDER=/app/frontend/build
            - ASPNETCORE_URLS=http://+:5001
            - ASPNETCORE_ENVIRONMENT=Development
        networks:
            - mywebsite-network

networks:
    mywebsite-network:
        driver: bridge
